In [12]:
import numpy as np

In [115]:
a = np.array(([8,4,2,3,9,1],[0,6,4,3,7,10],[2,0,1,3,5,8],[6,3,1,4,8,2],[0,2,4,3,5,9],[2,7,9,1,3,5]))
w = np.array(([2,0,3], [1,1,0], [3,-1,4]))
print(a)

[[ 8  4  2  3  9  1]
 [ 0  6  4  3  7 10]
 [ 2  0  1  3  5  8]
 [ 6  3  1  4  8  2]
 [ 0  2  4  3  5  9]
 [ 2  7  9  1  3  5]]


In [35]:
def zero_pad(X, pad):
  return np.pad(X, ((pad,pad),(pad,pad)), 'constant')

In [118]:
print(zero_pad(a, 2))

[[ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  8  4  2  3  9  1  0  0]
 [ 0  0  0  6  4  3  7 10  0  0]
 [ 0  0  2  0  1  3  5  8  0  0]
 [ 0  0  6  3  1  4  8  2  0  0]
 [ 0  0  0  2  4  3  5  9  0  0]
 [ 0  0  2  7  9  1  3  5  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]]


In [38]:
def conv_single_step(X_slice, weights):
  return np.sum(X_slice * weights)

In [102]:
def convolution(X, weights):
  height, width = X.shape
  f, f = weights.shape
  H = int((height-f)+1)
  W = int((width-f)+1)
  Z = np.zeros((H,W))


  for h in range(H):
    vert_start = h
    vert_end = f+h
    for w in range(W):
        horiz_start = w
        horiz_end = f+w
        a_slice_prev = X[vert_start:vert_end , horiz_start:horiz_end]  
        Z[h, w] = conv_single_step(a_slice_prev, weights)

  return Z

In [121]:
feature_map = convolution(zero_pad(a, 2), w)
print(feature_map)

[[32.  8. 28. 22. 39.  4. 26.  3.]
 [ 0. 32. 22. 32. 42. 54. 21. 31.]
 [32. 10. 38. 38. 58. 55. 42. 36.]
 [24. 26. 33. 46. 64. 56. 49. 34.]
 [ 6. 14. 30. 27. 51. 82. 26. 45.]
 [26. 35. 52. 40. 71. 42. 34. 28.]
 [ 0.  8. 21. 29. 33. 37. 18. 23.]
 [ 6. 21. 31. 17. 27. 17.  6. 10.]]


In [111]:
def pool(X, pool_size, stride, mode='max'):
    height, width = X.shape
    f = pool_size
    H = int(1 + (height - f) / stride)
    W = int(1 + (width - f) / stride)
    A = np.zeros((H,W))

    for h in range(H):
        vert_start = h * stride
        vert_end = f + h * stride

        for w in range(W):
            horiz_start = w * stride
            horiz_end = f + w * stride
            
            a_prev_slice = X[vert_start:vert_end , horiz_start:horiz_end]
                
            if mode == "max":
                A[h, w] = np.max(a_prev_slice)
            elif mode == "average":
                A[h, w] = np.mean(a_prev_slice)
    return A

In [122]:
print(pool(feature_map, 2, 2, 'max'))

[[32. 32. 54. 31.]
 [32. 46. 64. 49.]
 [35. 52. 82. 45.]
 [21. 31. 37. 23.]]
